# Generated by Django 5.0.6 on 2024-07-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Poster'),
        ),
    ]
